spring:
  #Configuracion del data source
  datasource:
    url: jdbc:h2:mem:renderdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  #configuracion de JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          url: jdbc:h2:mem:renderdb;DB_CLOSE_DELAY=-1;MODE=MySQL
  sql:
    init:
      mode: never

app:
  name: SpringLab CI/CD
  version: ${APP_VERSION:dev}
  build-number: ${BUILD_NUMBER:0}
  commit-hash: ${COMMIT_HASH:unknown}
#Configurar el servidor embebido (Tomcat)
server:
  port: 8080