spring:
  # Configuración del data source
  datasource:
    url: jdbc:mysql://localhost:3306/spring_lab?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configuración de JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Configuración de Jackson
  jackson:
    serialization:
      write-dates-as-timestamps: false

  # Configurar DevTools
  devtools:
    restart:
      enabled: true

# Configuración de la aplicación (fuera de spring)
app:
  name: SpringLab CI/CD
  version: ${APP_VERSION:dev}
  build-number: ${BUILD_NUMBER:0}
  commit-hash: ${COMMIT_HASH:unknown}

# Configurar el servidor embebido (Tomcat)
server:
  port: 8080